class ActivityModel {
  static const Map<String, List<String>> activities = {
    'Malaysia': [
      'Explore Kuala Lumpur City Center (KLCC) and the Petronas Towers.',
      'Visit Batu Caves near Kuala Lumpur.',
      'Enjoy the beautiful beaches in Langkawi.',
      'Discover the historic city of Melaka.',
      'Trek through Taman Negara National Park.',
      'Experience local culture and street food in Penang.',
      'Visit the Cameron Highlands for tea plantations and cool climate.',
      'Dive in the crystal-clear waters of Sipadan Island.',
    ],
    'China': [
      'Walk on the Great Wall of China.',
      'Explore the Forbidden City in Beijing.',
      'Cruise the Li River in Guilin.',
      'Visit the Terracotta Army in Xi\'an.',
      'Experience the vibrant atmosphere of Shanghai.',
      'Hike the stunning landscapes of Zhangjiajie National Forest Park.',
      'Discover the ancient city of Pingyao.',
      'Explore the historic architecture of Suzhou.',
    ],
    'India': [
      'Visit the Taj Mahal in Agra.',
      'Explore the vibrant city of Jaipur.',
      'Experience the chaos and beauty of Varanasi.',
      'Discover the historic city of Delhi.',
      'Relax on the beaches of Goa.',
      'Explore the backwaters of Kerala.',
      'Trek in the Himalayas, such as in Himachal Pradesh or Uttarakhand.',
      'Visit the ancient temples of Khajuraho.',
    ],
    'Thailand': [
      'Explore the bustling city of Bangkok.',
      'Relax on the beautiful beaches of Phuket.',
      'Visit the historic city of Ayutthaya.',
      'Experience the vibrant street life in Chiang Mai.',
      'Discover the stunning islands of Krabi Province.',
      'Explore the ancient city of Sukhothai.',
      'Visit the floating markets in Damnoen Saduak.',
      'Experience the nightlife in Pattaya.',
    ],
    'Korea': [
      'Explore the vibrant city of Seoul.',
      'Visit Gyeongbokgung Palace and Bukchon Hanok Village.',
      'Experience the lively atmosphere of Myeongdong.',
      'Discover the beautiful landscapes of Jeju Island.',
      'Explore the historic city of Gyeongju.',
      'Visit the DMZ (Demilitarized Zone) on the border with North Korea.',
      'Experience traditional tea culture in Boseong Green Tea Fields.',
      'Try Korean barbecue and street food in local markets.',
    ],
    'Japan': [
      'Explore the bustling city of Tokyo.',
      'Visit Kyoto and its historic temples and gardens.',
      'Experience the unique culture of Osaka.',
      'Discover the beauty of Mount Fuji.',
      'Explore the historic district of Gion in Kyoto.',
      'Visit the deer in Nara Park.',
      'Experience traditional tea ceremonies in Uji.',
      'Relax in an onsen (hot spring) in Hakone.',
    ],
  };
}
